# Random

## Difference entre random.randint() & randrom.randrange()

### random.randint(0 [start], 10 [end]) :

Genère un entier entre entre 0 et 10 (inclus).

### random.randint(0 [start], 10 [end], 1 [step]) :

Genère un entier entre 0 et 10 (exclus)

In [14]:
import random

print(random.randint(0, 10)) # random int from [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(random.randrange(0, 10, 2)) # random int from [0, 2, 4, 6, 8]

4
4


# random.choices() & random.sample()

### random.choices(population, k=1) :
Sélectionne k éléments avec remise depuis une population (les éléments peuvent être répétés).

### random.sample(population, k) :
Sélectionne k éléments sans remise depuis une population (tous les éléments sont uniques).

#### Args :
- population : La séquence source depuis laquelle sélectionner les éléments (liste, tuple, string, set, etc.)
- k : Le nombre d'éléments à sélectionner (doit être ≤ len(population))

In [24]:
liste = [1, 2, 3, 4, 5]

# Avec remise - peut avoir des doublons
choices = random.choices(liste, k=3)  # Peut donner [2, 2, 5]

# Sans remise - tous uniques
sample = random.sample(liste, 3)     # Peut donner [1, 4, 2]

print(f"""
    choices: {choices} 
    sample: {sample}
""")


    choices: [3, 3, 1] 
    sample: [3, 4, 1]



# Numpy

## .T (Transpose)
Transpose la matrice. Pour un tableau 1D, retourne le tableau original.

In [3]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.T)
# [[1 4]
#  [2 5]
#  [3 6]]

arr_1d = np.array([1, 2, 3])
print(arr_1d.T)  # [1 2 3] (inchangé)

[[1 4]
 [2 5]
 [3 6]]
[1 2 3]


## .data
Pointeur vers la position mémoire des données du tableau.

In [6]:
arr = np.array([1, 2, 3, 4])
print(arr.data)  # <memory at 0x...>

# Exemple d'utilisation avec des vues
view = arr[1:3]
print(view.data)  # Pointe vers la même zone mémoire

## .dtype
Type de données des éléments du ndarray.


In [9]:
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)  # int64

arr_float = np.array([1.5, 2.7, 3.2])
print(arr_float.dtype)  # float64

arr_str = np.array(['a', 'b', 'c'])
print(arr_str.dtype)  # <U1

int64
float64
<U1


## .flags
Informations sur le stockage en mémoire du ndarray.

In [12]:
arr = np.array([1, 2, 3, 4])
print(arr.flags)
# C_CONTIGUOUS : True
# F_CONTIGUOUS : True
# OWNDATA : True
# WRITEABLE : True
# ALIGNED : True
# WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## .imag
Partie imaginaire des données du ndarray (pour nombres complexes).

In [15]:
arr_complex = np.array([1+2j, 3+4j, 5+6j])
print(arr_complex.imag)  # [2. 4. 6.]

arr_real = np.array([1, 2, 3])
print(arr_real.imag)  # [0 0 0]

[2. 4. 6.]
[0 0 0]


## .size
Le nombre total d'éléments dans le ndarray.

In [18]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d.size)  # 4

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.size)  # 6 (2×3)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.size)  # 8 (2×2×2)

4
6
8


## .ndim
Le nombre de dimensions du ndarray.

In [22]:
arr_1d = np.array([1, 2, 3])
print(arr_1d.ndim)  # 1

arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.ndim)  # 2

arr_3d = np.array([[[1, 2]], [[3, 4]]])
print(arr_3d.ndim)  # 3

1
2
3


## .shape
La forme du ndarray (tuple des dimensions).